spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/ex-oauth;MODE=MYSQL
      username: sa

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        use_sql_comment: true
        default_batch_fetch_size: 100
    open-in-view: false

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true



logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace